import { PageHero } from '@/components/ui/PageHero'
import { Section } from '@/components/ui/Section'
import { useSeo } from '@/lib/useSeo'

const SECTIONS = [
  {
    h: 'Scope of this policy',
    p: 'This Privacy Policy describes how Emagia, Inc. ("Emagia", "we", "us") collects, processes, and protects personal information through its websites, marketing surfaces, and the Gia agent platform. It applies to visitors, prospects, customers, and authorized end-users.',
  },
  {
    h: 'Information we collect',
    p: 'We collect information you provide directly (e.g. contact form, demo requests, support tickets), information automatically generated by your use of the Gia platform (e.g. usage telemetry, audit logs), and information from third parties (e.g. enrichment data, ERP integration metadata). For each category, we retain only what we need to deliver the contracted service.',
  },
  {
    h: 'How we use information',
    p: 'To provide and operate the Gia agent platform, to deliver customer-requested services and support, to meet legal obligations (including audit and compliance), to improve the platform via aggregated insights, and to communicate with you about your account or our product roadmap. We do not sell personal information.',
  },
  {
    h: 'Legal bases (GDPR)',
    p: 'We process personal data under one of: contractual necessity, legitimate interest, consent (which you can withdraw at any time), or legal obligation. EU/UK visitors can request our Article 30 Records of Processing Activity at privacy@emagia.com.',
  },
  {
    h: 'Sharing & sub-processors',
    p: 'We share information only with sub-processors required to deliver the Gia service (e.g. cloud infrastructure, telemetry, transactional email). A current list of sub-processors is available upon request. We never sell personal information to third parties.',
  },
  {
    h: 'Security',
    p: 'Emagia maintains SOC 2 Type II certification, ISO 27001 alignment, and GDPR-compliant data processing. Customer data is encrypted in transit (TLS 1.2+) and at rest (AES-256). Access is role-based, MFA-enforced, and fully audited.',
  },
  {
    h: 'Data retention',
    p: 'We retain personal data only as long as needed for the purpose collected, plus the periods required by law (e.g. tax, audit). Customer AR data is retained per the active customer contract; default retention is mirrored to the customer’s configured ERP system.',
  },
  {
    h: 'Your rights',
    p: 'Subject to applicable law, you may access, correct, port, restrict, or delete personal data we hold about you. To exercise a right, write to privacy@emagia.com. We respond within 30 days.',
  },
  {
    h: 'International transfers',
    p: 'Emagia is headquartered in the United States and operates globally. Where personal data is transferred from the EU/UK, we rely on Standard Contractual Clauses and supplementary measures consistent with EDPB guidance.',
  },
  {
    h: 'Cookies & tracking',
    p: 'The Emagia marketing site uses a minimal first-party analytics set to understand aggregate page performance. We do not use third-party advertising trackers. You can disable cookies in your browser without impacting any product functionality.',
  },
  {
    h: 'Updates to this policy',
    p: 'We may update this policy from time to time. Material changes are announced via email to customers and via this page. The “Last updated” date below reflects the current version.',
  },
  {
    h: 'Contact',
    p: 'Privacy questions: privacy@emagia.com. Data Protection Officer (EU/UK): dpo@emagia.com. Postal mail: Emagia, Inc., Santa Clara, California, United States.',
  },
]

export default function LegalPrivacy() {
  useSeo({
    title: 'Privacy Policy | Emagia',
    description:
      'How Emagia collects, processes, and protects personal information across the Gia agent platform and marketing surfaces. SOC 2 Type II · ISO 27001 · GDPR-aligned.',
  })
  return (
    <>
      <PageHero
        eyebrow="Legal · Privacy Policy"
        title="How Emagia handles "
        titleAccent="your data."
        lede="The short version: we collect only what we need to deliver the contracted service, we never sell personal information, we encrypt everything in transit and at rest, and we honour every data-subject right in the applicable jurisdiction. The long version is below."
      />
      <Section className="!pt-0">
        <p className="text-[13px] text-muted mb-10">Last updated: April 2026</p>
        <div className="grid lg:grid-cols-12 gap-10">
          <nav aria-label="Sections" className="lg:col-span-3 lg:sticky lg:top-24 lg:self-start">
            <p className="text-[12px] uppercase tracking-[0.18em] text-soft font-medium mb-3">On this page</p>
            <ul className="space-y-2 text-[13px]">
              {SECTIONS.map((s) => (
                <li key={s.h}>
                  <a href={`#${slug(s.h)}`} className="text-muted hover:text-cyan transition-colors">
                    {s.h}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
          <article className="lg:col-span-9 space-y-12">
            {SECTIONS.map((s) => (
              <section key={s.h} id={slug(s.h)} className="scroll-mt-24">
                <h2 className="text-white text-[22px] font-semibold tracking-tight">{s.h}</h2>
                <p className="mt-4 text-[15.5px] text-soft leading-[1.7]">{s.p}</p>
              </section>
            ))}
          </article>
        </div>
      </Section>
    </>
  )
}

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
